Add support for Node.js v26 (#2520)
Bump `@ericcornelissen/lregexp` to get a version supporting
Node.js v26.

Disable coverage for runtime compatibility tests in CI because
it currently fails on Node.js v26 due to the use of `yargs` by `c8`
with the error:

    const {applyExtends, cjsPlatformShim, Parser, Yargs, processArgv} =
    require('./build/index.cjs')
    ReferenceError: require is not defined in ES module scope, you can
    use import instead
        ...